Repository N-NProject/frontend, pull requests merged in 2024-10, with the labels that each got.

#51 kakao로그인 , 마이페이지 api연동 로그아웃 버튼 생성
  my-app/.gitignore
  my-app/package.json
  my-app/src/app/layout.tsx
  my-app/src/app/login/page.tsx
  my-app/src/app/mypage/page.tsx
  my-app/src/app/page.tsx
  my-app/src/components/navweb.tsx
  my-app/yarn.lock
Labels: ✨ Feature, 📬 API

#48 feat:채팅 관련 기능 구현 완료, 변수 이름 변경 등 수정사항 반영
  my-app/src/app/boards/page.tsx
  my-app/src/app/chat/[[...slug]]/page.tsx
  my-app/src/app/page.tsx
  my-app/src/app/post/[slug]/page.tsx
  my-app/src/components/ConfirmModal.tsx
  my-app/src/components/PostPreview.tsx
  my-app/src/types/boards.ts
Labels: ✨ Feature, 📬 API

#61 fix: 변수 이름 수정, 이미지 추가, 배포 시 발생한 오류 수정
  my-app/src/app/alarm/page.tsx
  my-app/src/app/boards/page.tsx
  my-app/src/app/chat/[[...slug]]/page.tsx
  my-app/src/app/mypage/page.tsx
  my-app/src/assets/mypage/thumbnail.svg
  my-app/src/assets/previewImages/Boardgame.png
  my-app/src/assets/previewImages/CoffeeChat.png
  my-app/src/assets/previewImages/NoImage.png
  my-app/src/components/NotificationItem.tsx
  my-app/src/components/PostPreview.tsx
  my-app/src/components/nav.tsx
  my-app/src/components/navweb.tsx
  my-app/src/types/boards.ts
Labels: 🐞 BugFix

#63 fix/배포오류 수정
  my-app/src/app/login/page.tsx
  my-app/src/app/mypage/page.tsx
  my-app/src/components/SideBar.tsx
  my-app/src/components/navweb.tsx
  my-app/yarn.lock
Labels: 🐞 BugFix

#67 fix/배포오류 수정 및 반응형 디자인, 컴포넌트 디자인 수정
  my-app/package.json
  my-app/public/icons/logo.png
  my-app/src/app/layout.tsx
  my-app/src/app/login/page.tsx
  my-app/src/app/mypage/page.tsx
  my-app/src/components/PostPreview.tsx
  my-app/src/components/nav.tsx
  my-app/src/components/navweb.tsx
  my-app/yarn.lock
Labels: 🐞 BugFix, 🎨 Publising

#72 작성 참여 게시글 목록 수정 & 반응형 수정
  my-app/src/app/mypage/page.tsx
Labels: 🐞 BugFix
